### PR TITLE
chore: explicit service name edit and organise script setting panel

### PR DESCRIPTION
**Pull request by kyungeunni**
Part of https://ubio-automation.atlassian.net/jira/software/projects/ROBO/boards/4?selectedIssue=ROBO-399
Follow spec for `edit-default` panel.
Also when the service name is updated, it tries to update the serviceName on AC, rather than waiting for next save.
image

### CODE REVIEW

**Comment by inca** [comment]
> Also when the service name is updated, it tries to update the serviceName on AC, rather than waiting for next save.

Is this feature specifically requested? Sounds a bit controversial to me wrt UX, as is the fact that only Automation name is saved-upon-edit and not other properties within the same group.

**Comment by kyungeunni** [comment]
It's not requested, but while QAing the flow, I observed that the service name from AC  is not the same as the local service name when the name is updated locally. So when I open the Save modal or Open modal, I see different serviceName shown so it is confusing and I will never know if I'm going to override/replace the service name on AC or not by just saving the new version. 

we can change it to update other metadata too when it's changed to make the same behaviour, or if you have a better suggestion, please share 🙌

**Comment by inca** [comment]
Yeah, we definitely need a better way, esp. given that "Save Automation" action is explicit — so I wouldn't expect any change to actually happen whilst I'm editing what is perceived to be "local changes" (at very least, the way everything else is implemented builds this expectation).

On save/load the automation should be pre-selected based on `metadata.serviceId` — how about showing a warning OR displaying the item a bit differently in that dialog in case it was renamed?

**Comment by kyungeunni** [comment]
Will close and start a new branch with the new spec

**Pull request closed without merging**
