### PR TITLE
chore: remove autopilot

### PR DESCRIPTION
**Pull request by DLeibner**

### CODE REVIEW

**Comment by randunel** [comment]
```
+10,587 −78,504 
```

FYI big changes are usually frowned upon, but not banned. Linter fixes and vulnerabilities fixes should be in separate PRs.

**Comment by DLeibner** [comment]
> ```
> +10,587 −78,504 
> ```
> 
> 
>      
>   
> 
> FYI big changes are usually frowned upon, but not banned. Linter fixes and vulnerabilities fixes should be in separate PRs.

I totally agree with you. It's just that removing completely autopilot from the repo triggered other tasks and it didn't felt as a whole until those were done here as well. For instance I had to ensure that nothing is broken so lint showed minor warning which I fixed immediately. I had to remove dependencies from autopilot in package-lock and because of using workspaces in package.json there is only 1 common package-lock file. In order to generate a new one the easiest way was to delete it and run npm install which then updated all the dependencies and their dependencies which caused a problem with minipass which is a dependency of a dependency. Then I though since I have to deal with dependency versions I could fix vulnerabilities as well and luckily there were just several breaking changes that needed to be adapted, such as uuid and multer. I know that it is a big change which requires testing but I think it had to be done sooner or later :)

**Comment by DLeibner** [comment]
I have tested that `autopilot-app` repo works with these changes. I did the following steps to link engine and fuzzy-search as local dependencies:

- copy engine and fuzzy-search folders to new folder outside of the repo
- remove .npmrc files so that package-lock can be generated
- run npm install in each folder
- in package.json in autopilot-app/apps/autopilot repo add relative paths to folders from above
```
        "@automationcloud/engine": "file:../../../local-dependencies/engine",
        "@automationcloud/fuzzy-search": "file:../../../local-dependencies/fuzzy-search",
```
- run npm run compile
- run npm run ap
- autopilot app is running and prepared scenario from robot school is executed and it works

**Comment by inca** [comment]
Please make sure the problems mentioned in https://github.com/automationcloud/autopilot/pull/127 are addressed. After removing Autopilot from this repo, the build target becomes the worker — so the entire build pipeline should be in the working state.

Also let's not forget to rename the repositories appropriately, otherwise it will become quite messy.

**Pull request merged**
